name: sand-game
version: 1.0.0
summary: A simple falling sand game.
description: |
  A simple game about falling sand. It's build using flutter and dart.
confinement: strict
base: core18
grade: stable

apps:
  sand-game:
    command: sand_game
    extensions: [flutter-master]

parts:
  sand-game:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart